export const METRIC_DESCRIPTIONS: Record<string, string> = {
  activePersonnel: "Number of active military personnel.",
  reservePersonnel: "Number of reserve personnel.",
  paramilitary: "Number of paramilitary forces.",
  defenseBudgetUsd: "Annual defense budget in US dollars.",
  gdpUsd: "Gross domestic product in US dollars.",
  population: "Total population.",
  landAreaKm2: "Land area in square kilometers.",
  aircraft: "Total number of aircraft.",
  fighterJets: "Number of fighter jets.",
  attackHelicopters: "Number of attack helicopters.",
  transportHelicopters: "Number of transport helicopters.",
  tanks: "Number of main battle tanks.",
  armoredVehicles: "Number of armored fighting vehicles.",
  selfPropelledArtillery: "Number of self‑propelled artillery pieces.",
  rocketProjectors: "Number of rocket launchers.",
  navalVessels: "Total naval vessels.",
  submarines: "Number of submarines.",
  destroyers: "Number of destroyers.",
  frigates: "Number of frigates.",
  aircraftCarriers: "Number of aircraft carriers.",
  nuclearWarheads: "Number of nuclear warheads.",
};
export default METRIC_DESCRIPTIONS;